### ISSUE TITLE
`toVariants()` missing ?!

### ISSUE THREAD

**Issue by S1SYPHOS** [HashandSalt/kirby3-webp#4]
Hey there,
the latest release removed sure a hell of methods, leading to the snippet not working anymore - what happened there?

:)

**Comment by HashandSalt** [comment]
Thats odd.. just moved the the dependency in to the main file. Just pushed again, have another go 👍

**Comment by HashandSalt** [comment]
Sorry @S1SYPHOS I accidently pushed an old branch. Give it a go now 👍

**Comment by S1SYPHOS** [comment]
I was kinda shocked :D thx
