### ISSUE TITLE
Missing `alt` attribute

### ISSUE THREAD

**Issue by S1SYPHOS** [HashandSalt/kirby3-webp#5]
Did you mean `$alt` on this line?
https://github.com/HashandSalt/kirby3-webp/blob/772b3fd50f0dc5bf8f958dd5b701024198198f6c/snippets/webp.php#L31

You are building `$tag->alt`, but never use it anywhere, so I'm wondering ..

**Comment by HashandSalt** [comment]
It reads it from the files meta content. Best practice to put an Alt field in there :)  Its missing from your image file blueprint, rather than the plugin.

**Comment by S1SYPHOS** [comment]
I should just go to bed .. thanks for clarifying! What about width/height of the `<img>` tag?
