### ISSUE TITLE
`Call to a member function resize() on null`

### ISSUE THREAD

**Issue by afbora** [HashandSalt/kirby3-webp#8]
I'm getting following error when using `(webp: test.webp)`

> Call to a member function resize() on null
> \site\plugins\kirby3-webp-master\snippets\webp.php:30

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by HashandSalt** [comment]
Thanks @afbora - i will archive this plugin now since Kirby supports WebP natively.

**Comment by afbora** [comment]
OK. I'll move to archived this plugin now for getkirby.com directory (will be removed when K4 released).
